import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { supabase } from "../utils/supabase";

const Home: NextPage = () => {
  const [file, setFile] = useState<File | null>(null);

  const onChange = async (evt: any) => {
    const fileFound = evt.target.files[0] as File;
    setFile(fileFound);
  };

  const onSubmit = async (evt: any) => {
    evt.preventDefault();
    if (file !== null) {
      const { error } = await supabase.storage.getBucket("test");
      if (error !== null && (error as any).status === 400) {
        await supabase.storage.createBucket("test", {
          public: true,
        });
      }
      const { error: errorUpdateCalFile } = await supabase.storage
        .from("test")
        .upload("avatar", file, {
          cacheControl: "3600",
          upsert: true,
        });
      console.error(errorUpdateCalFile);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Status: {file !== null ? "File charged" : "File empty"}</div>
        <br />
        <form onSubmit={onSubmit}>
          <input type="file" onChange={onChange} />
          <button type="submit">Submit</button>
        </form>
      </main>
    </div>
  );
};

export default Home;
